scp main.c pi@$(echo $pi_ip):~/KIMMINSU
scp baby_dev_MQTT.c pi@$(echo $pi_ip):~/KIMMINSU
scp baby_dev_mod_lib.c pi@$(echo $pi_ip):~/KIMMINSU
scp baby_dev_mknod.sh pi@$(echo $pi_ip):~/KIMMINSU
scp baby_dev_mod.ko pi@$(echo $pi_ip):~/KIMMINSU
scp baby_dev_mod_lib.h pi@$(echo $pi_ip):~/KIMMINSU
scp baby_dev_mod.h pi@$(echo $pi_ip):~/KIMMINSU
scp format_assembler.c pi@$(echo $pi_ip):~/KIMMINSU
scp hub_MQTT.c pi@$(echo $pi_ip):~/KIMMINSU
scp test.c pi@$(echo $pi_ip):~/KIMMINSU
scp baby_speaker.ko pi@$(echo $pi_ip):~/KIMMINSU
scp baby_speaker.h pi@$(echo $pi_ip):~/KIMMINSU
scp baby_speaker_lib.c pi@$(echo $pi_ip):~/KIMMINSU
scp baby_speaker_mknod.sh pi@$(echo $pi_ip):~/KIMMINSU
scp hub_lib.c pi@$(echo $pi_ip):~/KIMMINSU
